-- MySQL Script generated by MySQL Workbench
-- Tue Aug 29 11:01:41 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`entrees`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`entrees` (
  `identrée` INT NOT NULL,
  `nom` VARCHAR(45) NOT NULL,
  `description` VARCHAR(300) NOT NULL,
  `prix` VARCHAR(45) BINARY NOT NULL,
  `image` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`identrée`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Boissons`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Boissons` (
  `identrée` INT NOT NULL,
  `nom` VARCHAR(45) NOT NULL,
  `description` VARCHAR(300) NOT NULL,
  `prix` VARCHAR(45) BINARY NOT NULL,
  `image` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`identrée`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`plats`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`plats` (
  `identrée` INT NOT NULL,
  `nom` VARCHAR(45) NOT NULL,
  `description` VARCHAR(300) NOT NULL,
  `prix` VARCHAR(45) BINARY NOT NULL,
  `image` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`identrée`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`desserts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`desserts` (
  `identrée` INT NOT NULL,
  `nom` VARCHAR(45) NOT NULL,
  `description` VARCHAR(300) NOT NULL,
  `prix` VARCHAR(45) BINARY NOT NULL,
  `image` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`identrée`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`menu`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`menu` (
  `idmenu` INT NOT NULL,
  `menuName` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idmenu`),
  CONSTRAINT `entrees`
    FOREIGN KEY ()
    REFERENCES `mydb`.`entrees` ()
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `boissons`
    FOREIGN KEY ()
    REFERENCES `mydb`.`Boissons` ()
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `plats`
    FOREIGN KEY ()
    REFERENCES `mydb`.`plats` ()
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `desserts`
    FOREIGN KEY ()
    REFERENCES `mydb`.`desserts` ()
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`role` (
  `idtable1` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idtable1`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`user` (
  `iduser` INT NOT NULL,
  `Email` VARCHAR(45) NOT NULL,
  `nom` VARCHAR(45) NOT NULL,
  `prenom` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`iduser`),
  UNIQUE INDEX `Email_UNIQUE` (`Email` ASC) VISIBLE,
  CONSTRAINT `role`
    FOREIGN KEY ()
    REFERENCES `mydb`.`role` ()
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`restaurant`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`restaurant` (
  `idrestaurant` INT NOT NULL,
  `nom` VARCHAR(45) NOT NULL,
  `description` MEDIUMTEXT NULL,
  `adresse` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idrestaurant`),
  UNIQUE INDEX `adresse_UNIQUE` (`adresse` ASC) VISIBLE,
  CONSTRAINT `menu`
    FOREIGN KEY ()
    REFERENCES `mydb`.`menu` ()
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `user`
    FOREIGN KEY ()
    REFERENCES `mydb`.`user` ()
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`typeEvent`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`typeEvent` (
  `idtypeEvent` INT NOT NULL,
  `nom` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idtypeEvent`),
  UNIQUE INDEX `nom_UNIQUE` (`nom` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`team`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`team` (
  `idtable1` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `logo` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idtable1`),
  UNIQUE INDEX `logo_UNIQUE` (`logo` ASC) VISIBLE,
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Event`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Event` (
  `idtable1` INT NOT NULL,
  PRIMARY KEY (`idtable1`),
  CONSTRAINT `typeEvent`
    FOREIGN KEY ()
    REFERENCES `mydb`.`typeEvent` ()
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `team`
    FOREIGN KEY ()
    REFERENCES `mydb`.`team` ()
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `team2`
    FOREIGN KEY ()
    REFERENCES `mydb`.`team` ()
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`restaurantEvent`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`restaurantEvent` (
  `idrestaurantEvent` INT NOT NULL,
  PRIMARY KEY (`idrestaurantEvent`),
  CONSTRAINT `event`
    FOREIGN KEY ()
    REFERENCES `mydb`.`Event` ()
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `restaurant`
    FOREIGN KEY ()
    REFERENCES `mydb`.`restaurant` ()
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
